# Use MRAM internal storage implementation instead of flash-based
CONFIG_MEMFAULT_NCS_INTERNAL_FLASH_BACKED_COREDUMP=n
CONFIG_MEMFAULT_COREDUMP_STORAGE_NRF_MRAM=y

# Enable Zephyr Power Management so the "pm_suspend_to_idle" shell command
# and the power_*_time_ms Memfault metrics can be exercised on this board.
CONFIG_PM=y
