# This makefile just leverages the public tests/Makefile to collect all the Makefile_*.mk
# in the makefiles directory and then invokes them using recursive make (sorry).

export MFLT_TEST_SRC_DIR := $(abspath src)

include $(abspath ..)/tests/Makefile
