# Overlay for selecting CoAP for connecting to Memfault.
# Requires NCS >=2.8.0.

# Enable CoAP, disable HTTP
CONFIG_MEMFAULT_USE_NRF_CLOUD_COAP=y
CONFIG_MEMFAULT_HTTP_ENABLE=n

# nRF Cloud CoAP (required for Memfault CoAP uploads)
CONFIG_NRF_CLOUD=y
CONFIG_NRF_CLOUD_COAP=y
# Use the modem's internal UUID as the nRF Cloud client ID (for JWT auth)
CONFIG_NRF_CLOUD_CLIENT_ID_SRC_INTERNAL_UUID=y
CONFIG_MODEM_JWT=y

# Required to be able to use the nRF Cloud CoAP connection for FOTA image downloads
CONFIG_NRF_CLOUD_FOTA=y
CONFIG_DOWNLOADER_TRANSPORT_COAP=y

# Ensure Memfault device id matches nRF Cloud client id
CONFIG_MEMFAULT_NCS_DEVICE_ID_HW_ID=y
CONFIG_HW_ID_LIBRARY_SOURCE_UUID=y

# CoAP client (needs more stack and heap than HTTP)
CONFIG_COAP_CLIENT_BLOCK_SIZE=1024
CONFIG_COAP_CLIENT_STACK_SIZE=6144
CONFIG_COAP_CLIENT_THREAD_PRIORITY=0
CONFIG_AT_MONITOR_HEAP_SIZE=512

# Required for streaming large FOTA images from nRF Cloud over CoAP
CONFIG_HEAP_MEM_POOL_SIZE=12288

CONFIG_COAP_EXTENDED_OPTIONS_LEN_VALUE=192
CONFIG_NRF_CLOUD_COAP_MAX_USER_OPTIONS=2
CONFIG_COAP_CLIENT_MAX_EXTRA_OPTIONS=3
