manifest:
  projects:
    - name: nrf
      url: https://github.com/nrfconnect/sdk-nrf
      revision: f6b4550c9c384c93c390c33cad5edd3f4431d949  # v3.2.4 + nrf_cloud_coap_get_user_options()
      import: true
      import:
        path-blocklist: modules/lib/memfault-firmware-sdk
        name-blocklist:
          # unused, save the download
          - matter
    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: master
  self:
    path: memfault_demo_app
    import: submanifests
